[sources.in]
type = "stdin"

[sinks.ddog]
type = "datadog_metrics"
inputs = [ "to_metric" ]
default_api_key = "${DATADOG_API_KEY}"
default_namespace = "tb"
site = "${DATADOG_SITE}"

[sinks.console]
inputs = ["parse"]
type = "console"
encoding.codec = "json"

[sinks.tinybird]
inputs = ["parse"]
type = "http"
uri = "https://${TB_HOST}.tinybird.co/v0/events?name=datadog_integration&token=${TB_TOKEN}"
encoding.codec = "json"
encoding.only_fields = ["pipe_full_name"]

[transforms.parse]
type = "remap"
inputs = [ "in" ]
source = """
  . = parse_json!(.message)
"""

[transforms.to_metric]
type = "log_to_metric"
inputs = [ "parse" ]

  [[transforms.to_metric.metrics]]
  field = "count_error"
  namespace = "tb.pipes"
  type = "counter"

    [transforms.to_metric.metrics.tags]
    pipe_full_name = "{{pipe_full_name}}"